### ISSUE TITLE
code availability?

### ISSUE THREAD

**Issue by tessus** [ClipMenu/ClipMenu#6]
As I have mentioned in https://github.com/naotaka/ClipMenu/issues/4#issuecomment-70334324 it seems that the old project is dead.

Unfortunately the Swift code is not available, so I cannot even help coding and add the features I was looking for. Can I assume that ClipMenu 1.0 will not be open source?

**Comment by lindes** [comment]
In [a blog post](http://www.clipmenu.com/blog/2014/10/27/ripped-off-clipmenu-on-mac-app-store/), there was mention made of ClipMenu being released under the MIT license.  Was that only the 0.x series?  I'd love to have open source for this, if only because I'd like to audit the security of it, e.g. making sure that if I disable the iCloud features, that the stuff I clip never leaves my computer.  I'd very much like to see this released as [FOSS (Free and Open Source Software)](http://en.wikipedia.org/wiki/Free_and_open-source_software), if at all possible.  And by free, I'm concerned with the freedom aspects - I'd be happy to make a financial contribution for this wonderful functionality!

**Comment by foozee** [comment]
+1

**Comment by afreet** [comment]
I'm also interested in helping out with this project, if it ever gets revived

**Comment by afreet** [comment]
@naotaka - Are you there?  If you release the Swift version of the code, I would be happy to get it back to a regular dev/release cycle.  It appears that v1.0a has some issues with Sierra, at least for me :(

**Comment by afreet** [comment]
It appears this project has migrated to https://clipy-app.com/
